# Generated by Django 5.2.8 on 2025-12-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'analytics_user_agents',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante_id', models.CharField(db_column='vid', db_index=True, max_length=255)),
                ('primera_visita', models.DateTimeField(auto_now_add=True, db_column='pv', db_index=True)),
                ('ultima_visita', models.DateTimeField(auto_now=True, db_column='up')),
                ('ip', models.GenericIPAddressField(blank=True, db_column='ip', null=True)),
                ('tipo_dispositivo', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analitica.useragent')),
            ],
            options={
                'db_table': 'analytics_visitantes',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.CharField(db_column='sid', db_index=True, max_length=255, unique=True)),
                ('inicio', models.DateTimeField(db_column='ini', db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, db_column='dur', null=True)),
                ('conteo_paginas', models.IntegerField(db_column='cnp', db_index=True, default=0)),
                ('es_rebote', models.BooleanField(db_column='reb', db_index=True, default=False)),
                ('ultima_actividad', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visitante', models.ForeignKey(db_column='vid', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='analitica.visitante')),
            ],
            options={
                'db_table': 'analytics_sesiones',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('page_view', 'Pagina Vista'), ('custom_event', 'Evento'), ('conversion', 'Conversion'), ('error', 'Error')], db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('ruta', models.CharField(blank=True, db_index=True, max_length=2000)),
                ('hora', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='analitica.sesion')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analitica.visitante')),
            ],
            options={
                'db_table': 'analytics_eventos',
            },
        ),
        migrations.CreateModel(
            name='PaginaVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(db_index=True, max_length=2000)),
                ('nombre_pagina', models.CharField(blank=True, max_length=500)),
                ('hora', models.DateTimeField(db_index=True)),
                ('tiempo_en_pagina', models.IntegerField(blank=True, null=True)),
                ('referencia', models.URLField(blank=True)),
                ('utm_data', models.JSONField(blank=True, default=dict)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_vistas', to='analitica.sesion')),
                ('user_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analitica.useragent')),
            ],
            options={
                'db_table': 'analytics_pagina_vista',
                'indexes': [models.Index(fields=['hora'], name='analytics_p_hora_31a263_idx'), models.Index(fields=['ruta'], name='analytics_p_ruta_43e06b_idx'), models.Index(fields=['sesion'], name='analytics_p_sesion__045661_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['visitante_id'], name='analytics_v_vid_35f487_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['pais'], name='analytics_v_pais_5d4ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='visitante',
            index=models.Index(fields=['primera_visita'], name='analytics_v_pv_d734ce_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['inicio'], name='analytics_s_ini_b56b40_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['fin'], name='analytics_s_fin_34b1af_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['visitante', 'inicio'], name='analytics_s_vid_49bb22_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo', 'hora'], name='analytics_e_tipo_35cba0_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['visitante', 'hora'], name='analytics_e_visitan_956356_idx'),
        ),
    ]
