# Generated by Django 5.2.8 on 2025-12-09 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudadanos', '0002_ciudadano_sexo'),
        ('dependecias_municipales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dependencia_municipal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='dependecias_municipales.dependenciamunicipal')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('folio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/adjuntos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('visto', 'Visto'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='enviada', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.categoria')),
                ('ciudadano', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='ciudadanos.ciudadano')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='solicitudes.solicitud')),
            ],
        ),
    ]
