# Generated by Django 5.2.8 on 2025-12-10 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0002_ciudadano_sexo'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_creada', 'Solicitud Creada'), ('solicitud_actualizada', 'Solicitud Actualizada'), ('solicitud_completada', 'Solicitud Completada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('comentario_nuevo', 'Nuevo Comentario')], default='solicitud_actualizada', max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/comentarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='comentario',
            name='creado_por',
            field=models.CharField(default='Sistema', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/adjuntos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='ciudadanos.ciudadano'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('visto', 'Visto'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], db_index=True, default='enviada', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='folio',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['ciudadano', '-fecha_creacion'], name='solicitudes_ciudada_0730f7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='solicitudes_estado_e90d78_idx'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ciudadanos.ciudadano'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='solicitudes.solicitud'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['ciudadano', '-fecha_creacion'], name='solicitudes_ciudada_2f7236_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida'], name='solicitudes_leida_077e3e_idx'),
        ),
    ]
