# Generated by Django 5.2.8 on 2025-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(db_index=True, max_length=5)),
                ('colonia', models.CharField(db_column='col', max_length=255)),
                ('municipio', models.CharField(db_column='mun', max_length=255)),
                ('estado', models.CharField(db_column='est', max_length=100)),
                ('tipo', models.CharField(db_column='tp', max_length=100)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
